import type { Metadata } from 'next';
import { RedHatDisplay } from '@/global/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={RedHatDisplay.className}>{children}</body>
    </html>
  );
}
